### PR TITLE
Implement text wrap feature.

### PR DESCRIPTION
**Pull request by letsintegreat**
Implement text wrap feature for Song name and artist name, for #4.

### CODE REVIEW

**Comment by letsintegreat** [comment]
Screenshot of the working example:

**Comment by AmreshSinha** [comment]
Damn! Kudos!
I will test it and merge it! :blush: :+1:

**Comment by AmreshSinha** [comment]
image

Can the text truncation be improved on the second line? Elipsis is touching the border. Can you implement it such that it truncates in alignment with the above line?

image

**Comment by letsintegreat** [comment]
@AmreshSinha Oh lol, I added ellipsis after making the name align with the red name, yeah I will fix that.
Also, I am currently truncating at spaces only, so should I truncate between words?

**Comment by letsintegreat** [comment]
@AmreshSinha Oh lol, I added ellipsis after making the name aligned with the red line, yeah I'll fix that.
Also, right now I am only truncating at spaces, not in between the words, so instead of (fe...), my script will keep (feat...), but it will find a shorter font size that would make it fit before the red line.

**Comment by AmreshSinha** [comment]
Merged :+1: 
Great work! :blush:

**Pull request closed without merging**
