### PR TITLE
Theme Color Extraction

### PR DESCRIPTION
**Pull request by delivey**
Issue: #3 

Code is pretty self explanatory, rewrote some code for retrieving the `data` variable so I could make my code cleaner by using `await` instead of `then`, hopefully that's fine with you, if not, say so.

Let me know if anything is unclear.

### CODE REVIEW

**Review by AmreshSinha — COMMENTED** [review]
```npm i```
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Amresh\AppData\Roaming\npm-cache\_logs\2021-10-02T05_10_15_728Z-debug.log
```

https://pastebin.com/raw/Dy4Fum0G (Skip to 24)

What OS are you using?

**Comment by delivey** [comment]
I'm using Windows 10. 

This is weird, I didn't install any packages, can you try removing package-lock.json and installing again?

**Comment by AmreshSinha** [comment]
> I'm using Windows 10.
> 
> This is weird, I didn't install any packages, can you try removing package-lock.json and installing again?

Yeah, now it's fine. I can see there are 6k+ line changes in package-lock.json. But you haven't added any package. Can the change in package-lock be reverted as it's creating conflicts while installation.

**Comment by delivey** [comment]
Done. Sorry about that.

**Comment by AmreshSinha** [comment]
Everything Else is fine 👍 
Nice Implementation 🚀 
Merged ✔️

**Pull request merged**
