### PR TITLE
Improve accuracy for searching by name

### PR DESCRIPTION
**Pull request by delivey**
Issue: #8 

Nothing to explain here, few character fix.
Don't bother putting the `hacktoberfest-accepted` label here since such easy pull requests are against Hacktoberfest's values.

### CODE REVIEW

**Comment by AmreshSinha** [comment]
Keep the offset. Change value to 1 :+1:

**Comment by delivey** [comment]
Offset 1 still returns the 2nd most popular song (it's 0-indexed). If we want the most popular song, we have to either set the offset to 0 or just remove it. Since 0 is default, I think simply removing the argument is the cleanest way to do this.

What do you think?

**Comment by AmreshSinha** [comment]
okay so yeah keep offset to 0

**Comment by AmreshSinha** [comment]
I think keeping the params will be better as if someone uses it, then he will directly edit the params according to his needs.

**Comment by delivey** [comment]
Done.

**Comment by AmreshSinha** [comment]
Merged :heavy_check_mark:

**Pull request merged**
